"""
Email service — sends diabetes prediction report via SMTP
"""

import os
import logging
import aiosmtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText

logger = logging.getLogger(__name__)

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")
FROM_NAME = os.getenv("FROM_NAME", "DiabetesAI")


async def send_prediction_email(to_email: str, result, pdf_path=None) -> None:
    if not SMTP_USER or not SMTP_PASS:
        logger.warning("SMTP credentials not configured — email skipped")
        return

    subject = f"Your Diabetes Risk Report — {result.risk_level} Risk"

    # Build factor rows
    factor_rows = ""
    for f in result.top_factors:
        arrow = "↑" if f["direction"] == "increases" else "↓"
        color = "#ef4444" if f["direction"] == "increases" else "#22c55e"
        factor_rows += f"""
        <tr>
          <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">{f['display_name']}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;color:{color};font-weight:bold;">
            {arrow} {f['direction'].capitalize()} risk
          </td>
          <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;color:{color};">
            {f['shap_value']:+.3f}
          </td>
        </tr>
        """

    risk_colors = {"Low": "#22c55e", "Medium": "#f59e0b", "High": "#ef4444"}
    risk_color  = risk_colors.get(result.risk_level, "#6b7280")

    html = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="UTF-8"></head>
    <body style="margin:0;padding:0;background:#f9fafb;font-family:'Segoe UI',Arial,sans-serif;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;padding:32px 0;">
        <tr><td align="center">
          <table width="600" cellpadding="0" cellspacing="0"
                 style="background:#ffffff;border-radius:16px;overflow:hidden;
                        box-shadow:0 4px 24px rgba(0,0,0,0.08);">

            <!-- Header -->
            <tr>
              <td style="background:linear-gradient(135deg,#6366f1 0%,#8b5cf6 100%);
                         padding:32px 40px;text-align:center;">
                <h1 style="margin:0;color:#fff;font-size:24px;font-weight:700;">
                  🧬 Diabetes Risk Report
                </h1>
                <p style="margin:8px 0 0;color:rgba(255,255,255,0.8);font-size:14px;">
                  Powered by AI — for informational purposes only
                </p>
              </td>
            </tr>

            <!-- Risk Summary -->
            <tr>
              <td style="padding:32px 40px;">
                <div style="text-align:center;margin-bottom:28px;">
                  <div style="display:inline-block;background:{risk_color}20;
                              border:2px solid {risk_color};border-radius:100px;
                              padding:10px 32px;margin-bottom:12px;">
                    <span style="color:{risk_color};font-size:22px;font-weight:800;">
                      {result.risk_level} Risk
                    </span>
                  </div>
                  <p style="font-size:36px;font-weight:800;color:{risk_color};margin:0;">
                    {result.probability:.1f}%
                  </p>
                  <p style="color:#6b7280;font-size:14px;margin:4px 0 0;">
                    Predicted probability of diabetes
                  </p>
                </div>

                <!-- Top Factors -->
                <h3 style="color:#111827;font-size:16px;margin:0 0 12px;">
                  Key Contributing Factors
                </h3>
                <table width="100%" cellpadding="0" cellspacing="0"
                       style="border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
                  <thead>
                    <tr style="background:#f9fafb;">
                      <th style="padding:10px 12px;text-align:left;font-size:12px;
                                 color:#6b7280;font-weight:600;text-transform:uppercase;">Factor</th>
                      <th style="padding:10px 12px;text-align:left;font-size:12px;
                                 color:#6b7280;font-weight:600;text-transform:uppercase;">Effect</th>
                      <th style="padding:10px 12px;text-align:left;font-size:12px;
                                 color:#6b7280;font-weight:600;text-transform:uppercase;">SHAP</th>
                    </tr>
                  </thead>
                  <tbody>{factor_rows}</tbody>
                </table>

                <!-- Disclaimer -->
                <p style="margin:24px 0 0;font-size:12px;color:#9ca3af;
                           border-top:1px solid #e5e7eb;padding-top:16px;">
                  ⚠️ This report is generated by an AI model and is intended for
                  informational purposes only. Please consult a qualified healthcare
                  professional for medical advice and diagnosis.
                </p>
              </td>
            </tr>

            <!-- Footer -->
            <tr>
              <td style="background:#f9fafb;padding:20px 40px;text-align:center;
                         border-top:1px solid #e5e7eb;">
                <p style="margin:0;font-size:12px;color:#9ca3af;">
                  Model: {result.model_name} &nbsp;|&nbsp;
                  Accuracy: {result.model_metrics.get('accuracy',0)*100:.1f}% &nbsp;|&nbsp;
                  AUC: {result.model_metrics.get('roc_auc',0):.4f}
                </p>
              </td>
            </tr>

          </table>
        </td></tr>
      </table>
    </body>
    </html>
    """

    msg = MIMEMultipart("mixed")
    html_part = MIMEMultipart("alternative")
    html_part.attach(MIMEText(html, "html"))
    msg.attach(html_part)
    msg["Subject"] = subject
    msg["From"]    = f"{FROM_NAME} <{SMTP_USER}>"
    msg["To"]      = to_email
    
    if pdf_path and pdf_path.exists():
        from email.mime.application import MIMEApplication
        with open(pdf_path, "rb") as f:
            pdf_attachment = MIMEApplication(f.read(), _subtype="pdf")
            pdf_attachment.add_header('Content-Disposition', 'attachment', filename=pdf_path.name)
            msg.attach(pdf_attachment)

    await aiosmtplib.send(
        msg,
        hostname=SMTP_HOST,
        port=SMTP_PORT,
        username=SMTP_USER,
        password=SMTP_PASS,
        start_tls=True,
    )
    logger.info(f"Email sent to {to_email}")
